#include <engine/chunks.h>
#include <engine/tilemap.h>
#include <stdio.h>
#include <tests.h>
#include <tests/chunks.h>

void test_chunks(void) {
    printf(YELLOW "\nTesting chunks...\n" RESET);

    CHUNKS_start();

    chunk data = (chunk){0};
    CHUNKS_get(0, &data);
    tile(*map)[data.w][data.h] = (tile(*)[data.w][data.h])data.map;

    bool checks[] = {
        data.w == 8,
        data.h == 8,
        (*map)[0][0].mat == tile_dirt,
        (*map)[1][0].mat == tile_dirt,
        (*map)[2][0].mat == tile_dirt,
        (*map)[3][0].mat == tile_dirt,
        (*map)[0][0].coords_x == 0,
        (*map)[1][0].coords_x == 1,
        (*map)[2][0].coords_x == 2,
        (*map)[3][0].coords_x == 3,
        (*map)[0][0].coords_y == 1,
        (*map)[1][0].coords_y == 1,
        (*map)[2][0].coords_y == 1,
        (*map)[3][0].coords_y == 1,
        (*map)[4][0].mat == tile_null,
        (*map)[5][0].mat == tile_null,
        (*map)[6][0].mat == tile_null,
        (*map)[7][0].mat == tile_null,
        (*map)[0][1].mat == tile_null,
        (*map)[1][1].mat == tile_null,
        (*map)[2][1].mat == tile_null,
        (*map)[3][1].mat == tile_null,
        (*map)[4][1].mat == tile_null,
        (*map)[5][1].mat == tile_null,
        (*map)[6][1].mat == tile_null,
        (*map)[7][1].mat == tile_null,
        (*map)[0][2].mat == tile_wood,
        (*map)[1][2].mat == tile_wood,
        (*map)[2][2].mat == tile_wood,
        (*map)[3][2].mat == tile_wood,
        (*map)[0][2].coords_x == 4,
        (*map)[1][2].coords_x == 5,
        (*map)[2][2].coords_x == 6,
        (*map)[3][2].coords_x == 7,
        (*map)[0][2].coords_y == 6,
        (*map)[1][2].coords_y == 6,
        (*map)[2][2].coords_y == 6,
        (*map)[3][2].coords_y == 6,
        (*map)[4][2].mat == tile_null,
        (*map)[5][2].mat == tile_null,
        (*map)[6][2].mat == tile_null,
        (*map)[7][2].mat == tile_null,
        (*map)[0][3].mat == tile_null,
        (*map)[1][3].mat == tile_null,
        (*map)[2][3].mat == tile_null,
        (*map)[3][3].mat == tile_null,
        (*map)[4][3].mat == tile_null,
        (*map)[5][3].mat == tile_null,
        (*map)[6][3].mat == tile_null,
        (*map)[7][3].mat == tile_null,
        (*map)[0][4].mat == tile_stone,
        (*map)[1][4].mat == tile_stone,
        (*map)[2][4].mat == tile_stone,
        (*map)[3][4].mat == tile_stone,
        (*map)[0][4].coords_x == 8,
        (*map)[1][4].coords_x == 9,
        (*map)[2][4].coords_x == 10,
        (*map)[3][4].coords_x == 11,
        (*map)[0][4].coords_y == 6,
        (*map)[1][4].coords_y == 6,
        (*map)[2][4].coords_y == 6,
        (*map)[3][4].coords_y == 6,
        (*map)[4][4].mat == tile_null,
        (*map)[5][4].mat == tile_null,
        (*map)[6][4].mat == tile_null,
        (*map)[7][4].mat == tile_null,
        (*map)[0][5].mat == tile_null,
        (*map)[1][5].mat == tile_null,
        (*map)[2][5].mat == tile_null,
        (*map)[3][5].mat == tile_null,
        (*map)[4][5].mat == tile_null,
        (*map)[5][5].mat == tile_null,
        (*map)[6][5].mat == tile_null,
        (*map)[7][5].mat == tile_null,
        (*map)[0][6].mat == tile_metal,
        (*map)[1][6].mat == tile_metal,
        (*map)[2][6].mat == tile_metal,
        (*map)[3][6].mat == tile_metal,
        (*map)[4][6].mat == tile_null,
        (*map)[5][6].mat == tile_null,
        (*map)[6][6].mat == tile_null,
        (*map)[7][6].mat == tile_null,
        (*map)[0][6].coords_x == 12,
        (*map)[1][6].coords_x == 13,
        (*map)[2][6].coords_x == 14,
        (*map)[3][6].coords_x == 15,
        (*map)[0][6].coords_y == 0,
        (*map)[1][6].coords_y == 0,
        (*map)[2][6].coords_y == 0,
        (*map)[3][6].coords_y == 0,
        (*map)[0][7].mat == tile_null,
        (*map)[1][7].mat == tile_null,
        (*map)[2][7].mat == tile_null,
        (*map)[3][7].mat == tile_null,
        (*map)[4][7].mat == tile_null,
        (*map)[5][7].mat == tile_null,
        (*map)[6][7].mat == tile_null,
        (*map)[7][7].mat == tile_null,
    };

    expect("Loaded mocked chunk, checking tiles...", sizeof(checks), checks);

    CHUNKS_stop();
}
