#pragma once

// Main settings
#define WINDOW_TITLE "Game"
#define WINDOW_SIZE_X 320
#define WINDOW_SIZE_Y 180

#define MAIN_T_TARGET_FPS 60
#define FIXED_T_TARGET_FPS 60

#define STARTING_WINDOW_SIZE_X 1280
#define STARTING_WINDOW_SIZE_Y 720
#define MIN_WINDOW_SIZE_X 640
#define MIN_WINDOW_SIZE_Y 360



// Renderer
#define SPRITESHEET_PATH "res/textures/spritesheet.png"

#define SPRITESHEET_X 256
#define SPRITESHEET_Y 256
#define SPRITESHEET_CELL_X 8
#define SPRITESHEET_CELL_Y 8

#define SPRITESHEET_DIRT_MIN_X 0
#define SPRITESHEET_DIRT_MAX_X 3
#define SPRITESHEET_WOOD_MIN_X 4
#define SPRITESHEET_WOOD_MAX_X 7
#define SPRITESHEET_STONE_MIN_X 8
#define SPRITESHEET_STONE_MAX_X 11
#define SPRITESHEET_METAL_MIN_X 12
#define SPRITESHEET_METAL_MAX_X 15

#define COL_BLACK 0, 0, 0, 255
#define COL_WHITE 255, 255, 255, 255



// Sprites
#define STARTING_SPRITES_DYNARR_CAP 1024
#define Z_INDEX_TOTAL 256 // z_index is Sint8, varies from -127 to 127



// Tilemaps
#define TILEMAP_SIZE_X 1024
#define TILEMAP_SIZE_Y 1024

#define CHUNK_MEM_BUFFER_SIZE 1048576 // 2^20
#define CHUNK_TOTAL 1
#define CHUNK_001_PATH "data/chunks/001.json"



// Physics
#define STARTING_BODIES_DYNARR_CAP 1024
#define FABS_ZERO_DIFF 0.001f
