name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libusb-1.0-0-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Cache SDL3
        id: sdl3-cache
        uses: actions/cache@v4
        with:
          path: ~/cache
          key: sdl3-cache

      - if: ${{ steps.sdl3-cache.outputs.cache-hit != 'true' }}
        name: Build SDL3
        run: |
          git clone https://github.com/libsdl-org/SDL.git
          cd SDL
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build --prefix /usr
          mkdir ~/cache
          sudo cp /usr/lib/libSDL3* ~/cache
          sudo cp -r /usr/include/SDL3 ~/cache

      - name: Install SDL3
        run: |
          sudo cp ~/cache/libSDL3* /usr/lib/
          sudo cp -r ~/cache/SDL3 /usr/include/

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: 16
          platform: x64

      - name: Setup .env
        run: cp .env.sample .env

      - name: Test
        run: bin/test
